### ISSUE TITLE
Typo Mistake in the PyLadies Website

### ISSUE THREAD

**Issue by Bhupesh-V** [PyLadiesDelhi/pyladiesdelhi.github.io#8]
![error2](https://user-images.githubusercontent.com/34342551/51252371-a9d1eb00-19c1-11e9-8169-7283344dec87.png)

"maonf" instead of "among".

**Comment by sanchibansal340** [comment]
Hi. My name is Sanchi. I am a beginner in open source contribution. I would like to work on this issue. Is it possible to assign it to me?
Thanks in advance.

**Comment by vipulgupta2048** [comment]
Hello @sanchibansal340 Thanks for your interest in taking this up. Although this content is extremely old, we added it to the site as a placeholder for new content. Which never came. 

**Best course of action**: If you can talk to organizers and decide on to the best course of action from here on out. That would be great.

**Comment by sanchibansal340** [comment]
I don't understand. Where I might be able to find the names of the organisers?

**Comment by sanchibansal340** [comment]
There is one more bug in this HTML file as the meetup link is not valid anymore.

**Comment by Bhupesh-V** [comment]
> I don't understand. Where I might be able to find the names of the organisers?

I tried contacting the ILUG-D folks, but it looks like the repo is not maitained (no active maintainer)
Try to contribute in other projects that are beginner friendly
